server:
  port: 8761
  tomcat:
    threads:
      max: 200

spring:
  application:
    name: discovery-server

eureka:
  server:
    enable-self-preservation: true
    expected-client-renewal-interval-seconds: 30
    eviction-interval-timer-in-ms: 60000
    peer-node-connect-timeout-ms: 5000
    peer-node-read-timeout-ms: 5000
    peer-node-total-connections: 1000
    peer-node-connections-per-host: 500
  client:
    # A standalone server should not attempt to register to its own registry framework
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
  endpoint:
    health:
      show-details: when_authorized