server:
  port: 8012
  forward-headers-strategy: framework

spring:
  application:
    name: product-service
    
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: appuser
    url: jdbc:mysql://localhost:3311/product_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    password: apppassword
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 20000

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate #update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        '[format_sql]': 'true'

  data:
    redis:
      host: localhost
      port: 6379

  flyway:
    enabled: true # Enables Flyway migrations on application startup
    baseline-on-migrate: true # Prevents accidental execution against an empty database without a baseline
    locations:
      - classpath:db/migration
      - classpath:db/testdata

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://localhost:8081

    consumer:
      group-id: product-saga-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema.registry.url: http://localhost:8081
        specific.avro.reader: true

# ===================================================================
# FIXED OBSERVABILITY & TRACING CONFIGURATION
# ===================================================================
management:
  prometheus:
    metrics:
      export:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus" # Exposes endpoints for micrometer mapping


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    eureka-server-connect-timeout-seconds: 5
    eureka-server-read-timeout-seconds: 5
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

logging:
  pattern:
    level: "%5p [${spring.application.name:-},%X{traceId:-},%X{spanId:-}]"