
@host = http://localhost:8014
@baseUrl = {{host}}/api/v1/inventorys
@contentType = application/json

### ============================================================================
### Get Product By Id
### ============================================================================

GET {{baseUrl}}/product/1
Accept: application/json

### ============================================================================
### Update stock by Product Id
### ============================================================================

POST {{baseUrl}}/stock
Content-Type: {{contentType}}
Accept: application/json

{
  "productId": 104,
  "availableQuantity": 210
}